# Cloud Build設定ファイル
steps:
  # Dockerイメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/choral-rss-bot:$BUILD_ID', '.']
  
  # Dockerイメージをプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/notion-to-bigquery:$BUILD_ID']
  
  # Cloud Run Jobをデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'replace'
      - 'job.yaml'
      - '--region=asia-northeast1'
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'IMAGE_URL=gcr.io/$PROJECT_ID/choral-rss-bot:$BUILD_ID'

# タイムアウト設定
timeout: '1200s'

# サブスティテューション
substitutions:
  _REGION: 'asia-northeast1'

# 成果物の設定
images:
  - 'gcr.io/$PROJECT_ID/notion-to-bigquery:$BUILD_ID'